import { Injectable } from '@angular/core';
import { WorkOrdersTableViewModel } from '../viewModels/work-orders-table';

@Injectable({
  providedIn: 'root'
})
export class AllWorkOrdersTableService {

  workOrders: WorkOrdersTableViewModel[];

  constructor() {
    this.workOrders = [
      {
        id: 1,
        status: 'In Progress',
        type: 'Maintenance',
        initialValue: 1000,
        location: 'Building A',
        receivingDate: new Date('2022-03-15'),
        subTasksNumber: 3,
        actionsNeeded: 2,
        customer: 'ABC Company',
      },
      {
        id: 2,
        status: 'Completed',
        type: 'Installation',
        initialValue: 2000,
        location: 'Warehouse B',
        receivingDate: new Date('2022-03-18'),
        subTasksNumber: 5,
        actionsNeeded: 1,
        customer: 'XYZ Corporation',
      },
      {
        id: 3,
        status: 'Pending',
        type: 'Repair',
        initialValue: 1500,
        location: 'Facility C',
        receivingDate: new Date('2022-03-20'),
        subTasksNumber: 2,
        actionsNeeded: 3,
        customer: 'LMN Industries',
      },
      {
        id: 4,
        status: 'A7a',
        type: 'Inspection',
        initialValue: 1800,
        location: 'Office D',
        receivingDate: new Date('2022-03-22'),
        subTasksNumber: 4,
        actionsNeeded: 1,
        customer: 'PQR Solutions',
      },
      {
        id: 5,
        status: 'Completed',
        type: 'Upgrade',
        initialValue: 2200,
        location: 'Storage E',
        receivingDate: new Date('2022-03-25'),
        subTasksNumber: 6,
        actionsNeeded: 2,
        customer: 'LMN Industries',
      },
      {
        id: 1,
        status: 'In Progress',
        type: 'Maintenance',
        initialValue: 1000,
        location: 'Building A',
        receivingDate: new Date('2022-03-15'),
        subTasksNumber: 3,
        actionsNeeded: 2,
        customer: 'ABC Company',
      },
      {
        id: 2,
        status: 'Completed',
        type: 'Installation',
        initialValue: 2000,
        location: 'Warehouse B',
        receivingDate: new Date('2022-03-18'),
        subTasksNumber: 5,
        actionsNeeded: 1,
        customer: 'XYZ Corporation',
      },
      {
        id: 3,
        status: 'Pending',
        type: 'Repair',
        initialValue: 1500,
        location: 'Facility C',
        receivingDate: new Date('2022-03-20'),
        subTasksNumber: 2,
        actionsNeeded: 3,
        customer: 'LMN Industries',
      },
      {
        id: 4,
        status: 'In Progress',
        type: 'Inspection',
        initialValue: 1800,
        location: 'Office D',
        receivingDate: new Date('2022-03-22'),
        subTasksNumber: 4,
        actionsNeeded: 1,
        customer: 'PQR Solutions',
      },
      {
        id: 5,
        status: 'Completed',
        type: 'Upgrade',
        initialValue: 2200,
        location: 'Storage E',
        receivingDate: new Date('2022-03-25'),
        subTasksNumber: 6,
        actionsNeeded: 2,
        customer: 'LMN Industries',
      },
      {
        id: 1,
        status: 'In Progress',
        type: 'Maintenance',
        initialValue: 1000,
        location: 'Building A',
        receivingDate: new Date('2022-03-15'),
        subTasksNumber: 3,
        actionsNeeded: 2,
        customer: 'ABC Company',
      },
      {
        id: 2,
        status: 'Completed',
        type: 'Installation',
        initialValue: 2000,
        location: 'Warehouse B',
        receivingDate: new Date('2022-03-18'),
        subTasksNumber: 5,
        actionsNeeded: 1,
        customer: 'XYZ Corporation',
      },
      {
        id: 3,
        status: 'Pending',
        type: 'Repair',
        initialValue: 1500,
        location: 'Facility C',
        receivingDate: new Date('2022-03-20'),
        subTasksNumber: 2,
        actionsNeeded: 3,
        customer: 'LMN Industries',
      },
      {
        id: 4,
        status: 'In Progress',
        type: 'Inspection',
        initialValue: 1800,
        location: 'Office D',
        receivingDate: new Date('2022-03-22'),
        subTasksNumber: 4,
        actionsNeeded: 1,
        customer: 'PQR Solutions',
      },
      {
        id: 5,
        status: 'Completed',
        type: 'Upgrade',
        initialValue: 2200,
        location: 'Storage E',
        receivingDate: new Date('2022-03-25'),
        subTasksNumber: 6,
        actionsNeeded: 2,
        customer: 'LMN Industries',
      },
      {
        id: 1,
        status: 'In Progress',
        type: 'Maintenance',
        initialValue: 1000,
        location: 'Building A',
        receivingDate: new Date('2022-03-15'),
        subTasksNumber: 3,
        actionsNeeded: 2,
        customer: 'ABC Company',
      },
      {
        id: 2,
        status: 'Completed',
        type: 'Installation',
        initialValue: 2000,
        location: 'Warehouse B',
        receivingDate: new Date('2022-03-18'),
        subTasksNumber: 5,
        actionsNeeded: 1,
        customer: 'XYZ Corporation',
      },
      {
        id: 3,
        status: 'Pending',
        type: 'Repair',
        initialValue: 1500,
        location: 'Facility C',
        receivingDate: new Date('2022-03-20'),
        subTasksNumber: 2,
        actionsNeeded: 3,
        customer: 'LMN Industries',
      },
      {
        id: 4,
        status: 'In Progress',
        type: 'Inspection',
        initialValue: 1800,
        location: 'Office D',
        receivingDate: new Date('2022-03-22'),
        subTasksNumber: 4,
        actionsNeeded: 1,
        customer: 'PQR Solutions',
      },
      {
        id: 5,
        status: 'Completed',
        type: 'Upgrade',
        initialValue: 2200,
        location: 'Storage E',
        receivingDate: new Date('2022-03-25'),
        subTasksNumber: 6,
        actionsNeeded: 2,
        customer: 'LMN Industries',
      },
      {
        id: 1,
        status: 'In Progress',
        type: 'Maintenance',
        initialValue: 1000,
        location: 'Building A',
        receivingDate: new Date('2022-03-15'),
        subTasksNumber: 3,
        actionsNeeded: 2,
        customer: 'ABC Company',
      },
      {
        id: 2,
        status: 'Completed',
        type: 'Installation',
        initialValue: 2000,
        location: 'Warehouse B',
        receivingDate: new Date('2022-03-18'),
        subTasksNumber: 5,
        actionsNeeded: 1,
        customer: 'XYZ Corporation',
      },
      {
        id: 3,
        status: 'Pending',
        type: 'Repair',
        initialValue: 1500,
        location: 'Facility C',
        receivingDate: new Date('2022-03-20'),
        subTasksNumber: 2,
        actionsNeeded: 3,
        customer: 'LMN Industries',
      },
      {
        id: 4,
        status: 'In Progress',
        type: 'Inspection',
        initialValue: 1800,
        location: 'Office D',
        receivingDate: new Date('2022-03-22'),
        subTasksNumber: 4,
        actionsNeeded: 1,
        customer: 'PQR Solutions',
      },
      {
        id: 5,
        status: 'Completed',
        type: 'Upgrade',
        initialValue: 2200,
        location: 'Storage E',
        receivingDate: new Date('2022-03-25'),
        subTasksNumber: 6,
        actionsNeeded: 2,
        customer: 'LMN Industries',
      },
      {
        id: 1,
        status: 'In Progress',
        type: 'Maintenance',
        initialValue: 1000,
        location: 'Building A',
        receivingDate: new Date('2022-03-15'),
        subTasksNumber: 3,
        actionsNeeded: 2,
        customer: 'ABC Company',
      },
      {
        id: 2,
        status: 'Completed',
        type: 'Installation',
        initialValue: 2000,
        location: 'Warehouse B',
        receivingDate: new Date('2022-03-18'),
        subTasksNumber: 5,
        actionsNeeded: 1,
        customer: 'XYZ Corporation',
      },
      {
        id: 3,
        status: 'Pending',
        type: 'Repair',
        initialValue: 1500,
        location: 'Facility C',
        receivingDate: new Date('2022-03-20'),
        subTasksNumber: 2,
        actionsNeeded: 3,
        customer: 'LMN Industries',
      },
      {
        id: 4,
        status: 'In Progress',
        type: 'Inspection',
        initialValue: 1800,
        location: 'Office D',
        receivingDate: new Date('2022-03-22'),
        subTasksNumber: 4,
        actionsNeeded: 1,
        customer: 'PQR Solutions',
      },
      {
        id: 5,
        status: 'Completed',
        type: 'Upgrade',
        initialValue: 2200,
        location: 'Storage E',
        receivingDate: new Date('2022-03-25'),
        subTasksNumber: 6,
        actionsNeeded: 2,
        customer: 'LMN Industries',
      },
      {
        id: 1,
        status: 'In Progress',
        type: 'Maintenance',
        initialValue: 1000,
        location: 'A7a A',
        receivingDate: new Date('2022-03-15'),
        subTasksNumber: 3,
        actionsNeeded: 2,
        customer: 'ABC Company',
      },
      {
        id: 2,
        status: 'Completed',
        type: 'Installation',
        initialValue: 2000,
        location: 'Warehouse B',
        receivingDate: new Date('2022-03-18'),
        subTasksNumber: 5,
        actionsNeeded: 1,
        customer: 'XYZ Corporation',
      },
      {
        id: 3,
        status: 'Pending',
        type: 'Repair',
        initialValue: 1500,
        location: 'Facility C',
        receivingDate: new Date('2022-03-20'),
        subTasksNumber: 2,
        actionsNeeded: 3,
        customer: 'LMN Industries',
      },
      {
        id: 4,
        status: 'In Progress',
        type: 'Inspection',
        initialValue: 1800,
        location: 'Office D',
        receivingDate: new Date('2022-03-22'),
        subTasksNumber: 4,
        actionsNeeded: 1,
        customer: 'PQR Solutions',
      },
      {
        id: 5,
        status: 'Completed',
        type: 'Upgrade',
        initialValue: 2200,
        location: 'Storage E',
        receivingDate: new Date('2022-03-25'),
        subTasksNumber: 6,
        actionsNeeded: 2,
        customer: 'LMN Industries',
      },
      {
        id: 1,
        status: 'In Progress',
        type: 'Maintenance',
        initialValue: 1000,
        location: 'Building A',
        receivingDate: new Date('2022-03-15'),
        subTasksNumber: 3,
        actionsNeeded: 2,
        customer: 'ABC Company',
      },
      {
        id: 2,
        status: 'Completed',
        type: 'Installation',
        initialValue: 2000,
        location: 'Warehouse B',
        receivingDate: new Date('2022-03-18'),
        subTasksNumber: 5,
        actionsNeeded: 1,
        customer: 'XYZ Corporation',
      },
      {
        id: 3,
        status: 'Pending',
        type: 'Repair',
        initialValue: 1500,
        location: 'Facility C',
        receivingDate: new Date('2022-03-20'),
        subTasksNumber: 2,
        actionsNeeded: 3,
        customer: 'LMN Industries',
      },
      {
        id: 4,
        status: 'In Progress',
        type: 'Inspection',
        initialValue: 1800,
        location: 'Office D',
        receivingDate: new Date('2022-03-22'),
        subTasksNumber: 4,
        actionsNeeded: 1,
        customer: 'PQR Solutions',
      },
      {
        id: 5,
        status: 'Completed',
        type: 'Upgrade',
        initialValue: 2200,
        location: 'Storage E',
        receivingDate: new Date('2022-03-25'),
        subTasksNumber: 6,
        actionsNeeded: 2,
        customer: 'LMN Industries',
      },
    ];
  }

  getAllWorkOrders() : WorkOrdersTableViewModel[] {
    return this.workOrders;
  }
}
